name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm

      - name: npm install, build and test
        run: |
          npm install
          npm run test
          npm run build
