name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: npm
    - name: npm install, build and test
      run: |
        npm install
        npm run test
        npm run build
