name: CI

on:
  pull_request:
    branches: [master]
  merge_group:
    branches: [master]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: yarn

      - name: yarn install, build, test and lint
        run: |
          yarn install
          yarn run test
          yarn run build
          yarn run lint
